version: '2'
services:
  app:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - mypostgres
    - myredis
  mypostgres:
    image: postgres
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=adv_pass
    - POSTGRES_USER=adv_user
    - POSTGRES_DB=adv_works
  myredis:
    image: "redis:alpine"
    ports:
    - "6379:6379"