version: '3'
services:
  app:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - mypostgres
    - myredis
  mypostgres:
    image: postgres    
    ports:
    - "5432:5432"
    environment:
    - ADV_PASSWORD=adv_pass
    - ADV_USER=adv_user
    - ADV_DB=adv_works
    - POSTGRES_USER=postgres
    build: ./postgres-db
  myredis:
    image: redis:alpine
    ports:
    - "6379:6379"